services:
  cgit:
    image: ghcr.io/amrkmn/cgit:latest
    container_name: cgit
    hostname: cgit
    ports:
      - "8081:80"
      - "2222:22"
    volumes:
      - ./data/repositories:/opt/cgit/repositories
      - ./data/ssh:/opt/cgit/ssh
      - ./data/cache:/opt/cgit/cache
    environment:
      - PUID=1000
      - PGID=1000
      - CGIT_HOST=localhost
      - CGIT_PORT=2222
      - CGIT_OWNER=Your Name <email@example.com>
    restart: unless-stopped
