services:
  cgit:
    image: ghcr.io/amrkmn/cgit:latest
    container_name: cgit
    hostname: cgit
    ports:
      - "8081:80"
      - "2222:22"
      - "9418:9418"
    volumes:
      - ./data:/opt/cgit/data
    environment:
      - PUID=1000
      - PGID=1000
      - CGIT_HOST=localhost
      - CGIT_PORT=2222
      - CGIT_USER_NAME=Your Name
      - CGIT_USER_EMAIL=email@example.com
    restart: unless-stopped
